/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_moomoohk_JNotificationCenter_JNotificationCenter */

#ifndef _Included_com_moomoohk_JNotificationCenter_JNotificationCenter
#define _Included_com_moomoohk_JNotificationCenter_JNotificationCenter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moomoohk_JNotificationCenter_JNotificationCenter
 * Method:    showNotification
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_moomoohk_JNotificationCenter_JNotificationCenter_showNotification
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
