/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_moomoohk_JNotificationCenter_notifications_URLNotification */

#ifndef _Included_com_moomoohk_JNotificationCenter_notifications_URLNotification
#define _Included_com_moomoohk_JNotificationCenter_notifications_URLNotification
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moomoohk_JNotificationCenter_notifications_URLNotification
 * Method:    show
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_moomoohk_JNotificationCenter_notifications_URLNotification_show
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
